Datasets:
  train:
    class_name: FixedDatasetLoader
    batch_size: 29
    dataset:
      class_name: distsup.data.ChunkedDataset
      dataset:
        class_name: egs.scribblelens.data.ScribbleLensDataset
        split: train
        alignment_root: "data/scribblelens.paths.1.4b.zip"
        vocabulary: egs/scribblelens/tasman.alphabet.plus.space.mode5.json
      chunk_len: 96
      training: true
      varlen_fields: [image, alignment]
      drop_fields: [
        text,
        alignment_rle,
        page_side,
        page
      ]
    rename_dict:
      image: features
    shuffle: true
    num_workers: 4
    drop_last: True
  dev:
    class_name: PaddedDatasetLoader
    batch_size: 32
    dataset:
      class_name: egs.scribblelens.data.ScribbleLensDataset
      split: test
      alignment_root: "data/scribblelens.paths.1.4b.zip"
      vocabulary: egs/scribblelens/tasman.alphabet.plus.space.mode5.json
    rename_dict:
        image: features
    num_workers: 4
    drop_last: True

Model:
  class_name: distsup.models.GAN_representation_learners.GanRepresentationLearner
  image_height: 32
  encoder:
    class_name: distsup.modules.convolutional.ConvStack1D
    hid_channels: 70
    num_strided: 2
    num_dilated: 2
    num_postdil: 3
# Tą flagą zamieniam ConvStack1D w identyczność nie tracąc kompatybilności wstecznej
    identity: True
  reconstructor:
    class_name: distsup.modules.reconstructors.NullReconstructor
  gan_generator:
    class_name: distsup.modules.gan.generator_net.LinearGeneratorNet
    gan_config: True
  gan_discriminator:
    class_name: distsup.modules.gan.discriminator_net.DiscriminatorNet
    gan_config: True


Trainer:
  class_name: distsup.gan_trainer.TrainerForGan
  checkpointer:
    every_n_hours: 4
  learning_rate: 0.001
  learning_rate_scheduler:
    class_name: torch.optim.lr_scheduler.ReduceLROnPlateau
    factor: 0.5
    patience: 2
  output_frequency: 20
  num_epochs: 20
  optimizer_name: Adam


#to będzie wstrzyknięte do generatora, dyscriminatora oraz Trenera jako Klasa GanConfig
# distsup.modules.gan.data_types.GanConfig
# W ten sposób mogę współdzielić ustawienia między klasami.
# Jest to brzydki hack :(
gan_config:
# Ustawienie na 1 wyłącza funkcjonalnosć. Wzięte od Chińczyków
  concat_window: 1
  repeat: 1
# Uproszczenie zadania
# Zmniejszyłem do 7 dostępne literki
# W ScribleLensdataset biorę alignment mod 7 [egs/scribblelens/data.py:733]
# Trzeba zmienić
  dictionary_size: 70
# Tutaj definiujemy długość wyjścia z encodera
# Jeżeli alignment zawiera więcej literek, to po prostu przycinam tą ilość
  max_sentence_length: 25
# waga dla gp_penalty Chińskiego GANa
  gradient_penalty_ratio: 10.0
  # Discriminator part
  dis_steps: 3
  dis_emb_size: 41
  dis_hidden_1_size: 37
  dis_hidden_2_size: 31
  dis_learning_rate: 0.002
  # Generator part
  gen_steps: 1
  gen_hidden_size: 43
  gen_learning_rate: 0.001