Datasets:
  train:
    class_name: FixedDatasetLoader
    batch_size: 3
    dataset:
      class_name: distsup.data.ChunkedDataset
      dataset:
        class_name: egs.scribblelens.data.ScribbleLensDataset
        split: train
        alignment_root: "data/scribblelens.paths.1.4b.zip"
        vocabulary: egs/scribblelens/tasman.alphabet.plus.space.mode5.json
      chunk_len: 96
      training: true
      varlen_fields: [image, alignment]
      drop_fields: [
        text,
        alignment_rle,
        page_side,
        page
      ]
    rename_dict:
        image: features
    shuffle: true
    num_workers: 4
  dev:
    class_name: PaddedDatasetLoader
    batch_size: 32
    dataset:
      class_name: egs.scribblelens.data.ScribbleLensDataset
      split: test
      alignment_root: "data/scribblelens.paths.1.4b.zip"
      vocabulary: egs/scribblelens/tasman.alphabet.plus.space.mode5.json
    rename_dict:
        image: features
    # drop_fields: [text, alignment_rle, page_side, page]
    num_workers: 4

Model:
  class_name: distsup.models.GAN_representation_learners.GanRepresentationLearner
  image_height: 32
  encoder:
    class_name: distsup.modules.convolutional.ConvStack1D
    hid_channels: 68
    num_strided: 2
    num_dilated: 2
    num_postdil: 3
  reconstructor:
    class_name: distsup.modules.reconstructors.NullReconstructor
  aux_heads:
    enc_sup:
      layer: encoder
      target: alignment
      predictor:
        class_name: distsup.modules.predictors.FramewisePredictor
        aggreg: 1
        use_two_layer_predictor: False
      bp_to_main: True
  gan_data_manipulation:
    class_name: distsup.modules.gan.data_preparation.GanConcatedWindowsDataManipulation
    windows_size: 5
    max_sentence_length: 37
    repeat: 6


Trainer:
  checkpointer:
    every_n_hours: 4
#  gradient_clipping:
#    clip_norm: 10.0
  learning_rate: 0.001
  learning_rate_scheduler:
    class_name: torch.optim.lr_scheduler.ReduceLROnPlateau
    factor: 0.5
    patience: 2
  output_frequency: 20
  num_epochs: 30
  optimizer_name: Adam
#  polyak_decay:
#  - 0.998
